### PR TITLE
Update layout, no responsive yet

### PR DESCRIPTION
**Pull request by sarinac**
To-do [Ravin]
* Rewrite intro
* Delete `References` pages and move them to blogs

To-do [Sarina]
* Create a Youtube social button in footer (and add to `pelicanconf.py` if possible)
* Fix content/layout for Book/Course section
    * What short/single-sentence description do you want for each of these? @canyon289 
* Make responsive for mobile

Also my code is kinda messy for the About.md but my brain is no longer working, so feel free to point out anything that looks too bad.

### CODE REVIEW

**Comment by canyon289** [comment]
Thanks, will do both in next 12 hours.

**Comment by canyon289** [comment]
Book
> Free textbook on statistical modeling

Course section 
> Courses for professionals looking to learn applied statistics hands on

**Comment by canyon289** [comment]
Removed references page on main. Rebasing this PR will get those changes in

**Comment by sarinac** [comment]
Hey sorry for my delay this time! Work has me occupied.

For the catch-all/misc idea, what other examples do you have in mind for that? My initial reaction is that I want to be able to categorize as much as possible to prevent unorganized stuff from building up and so that it's just easy to find. For "conference planning", that still feels like it could go in the **talks** section (I could lay it out differently, like a table layout to make it more condensed).

**Comment by canyon289** [comment]
Its partly flexibility, its partly so i dont need to bother everytime I subtly change what I do.

**Comment by sarinac** [comment]
How's this? 
image

**Comment by canyon289** [comment]
amazing

**Comment by canyon289** [comment]
Ignore the lack of CSS formatting below, I dled the index.

Adding a list under boxes seems more disorganized. Adding another box for a catch all seems bad huh? I can ask you about this later though. This already is way better. Can I merge it before any conflicts come up? Thank you so much again

image

**Comment by canyon289** [comment]
I appreciate it

**Pull request merged**
